name: Deploy app to gh-pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  shinylive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Install Dependencies
        run: |
          Rscript -e 'install.packages("pak", repos="https://cran.rstudio.com")'
          Rscript -e 'pak::pkg_install("bennettoxford/opencodes@main")'

      - name: Deploy with shinylive
        uses: posit-dev/r-shinylive/.github/workflows/deploy-app.yaml@actions-v1
    permissions:
      pages: write
      id-token: write